Added columns for Employee Model
Bohdanvakh/employee_accounting pull request #1
Opened 2023-05-09 14:09 UTC by Bohdanvakh

2023-05-09 14:58 UTC, vasyl-kvasnitsa requested changes

2023-05-09 14:58 UTC, vasyl-kvasnitsa commented on test/models/employee_test.rb
> +require "test_helper"
File is useless

2023-05-09 14:58 UTC, vasyl-kvasnitsa commented on test/models/position_test.rb
> +class PositionTest < ActiveSupport::TestCase
File is useless

2023-05-09 14:58 UTC, vasyl-kvasnitsa commented on test/fixtures/positions.yml
> +
File is useless

2023-05-09 14:58 UTC, vasyl-kvasnitsa commented on test/fixtures/employees.yml
> +# This model initially had no columns defined. If you add columns to the
File is useless

2023-05-09 14:58 UTC, vasyl-kvasnitsa commented on app/models/employee.rb
> +end
add validations for attributes

2023-05-09 14:58 UTC, vasyl-kvasnitsa commented on app/models/position.rb
> +class Position < ApplicationRecord
add validations for attributes

2023-05-09 14:58 UTC, vasyl-kvasnitsa commented on db/migrate/20230509133628_add_columns_to_employee.rb
> +      t.integer :number
For the future: You can create a table with columns. No need for two separate migrations.

2023-05-09 14:58 UTC, kvasyaa commented on db/migrate/20230509133628_add_columns_to_employee.rb
> +      t.date :date_of_employment
for date columns better is `employed_on`, for datetime 'employed_at' but not `date_of_employment`

2023-05-09 14:58 UTC, vasyl-kvasnitsa commented on db/migrate/20230509133628_add_columns_to_employee.rb
> +      t.string :patronymic
what do you mean by `patronymic`?

2023-05-09 14:58 UTC, vasyl-kvasnitsa commented on db/migrate/20230509133628_add_columns_to_employee.rb
> +      t.string :first_name
better to have 'first_name' and 'last_name' instead of `surname`

2023-05-09 14:58 UTC, vasyl-kvasnitsa commented on db/migrate/20230509133628_add_columns_to_employee.rb
> +      t.integer :number
why do we need `number` column?

2023-05-09 15:04 UTC, Bohdanvakh commented on db/migrate/20230509133628_add_columns_to_employee.rb
> +      t.string :patronymic
"Кожен працівник характеризується табельним номером, прізвищем, ім'ям, по-батькові"
patronymic - по-батькові, можливо варто замінити на surname, а прізвище на last_name

2023-05-09 15:04 UTC, Bohdanvakh commented on db/migrate/20230509133628_add_columns_to_employee.rb
> +      t.integer :number
табельний номер, можливо краще заміню на personnel_number

2023-05-09 15:09 UTC, Bohdanvakh commented on db/migrate/20230509133628_add_columns_to_employee.rb
> +      t.integer :number
чи ми можемо використати id замість цього?

2023-05-09 15:18 UTC, kvasyaa commented on db/migrate/20230509133628_add_columns_to_employee.rb
> +      t.string :patronymic
use `first_`, `middle_`, and `last_name` for it

2023-05-09 15:19 UTC, vasyl-kvasnitsa commented on db/migrate/20230509133628_add_columns_to_employee.rb
> +      t.integer :number
we will use `id` for it

2023-05-15 10:47 UTC, vasyl-kvasnitsa requested changes

2023-05-15 10:47 UTC, vasyl-kvasnitsa commented on app/models/employee.rb
> +end
salary is based on department and employed_on, so no needs in `salary` column

2023-05-15 11:09 UTC, vasyl-kvasnitsa requested changes

2023-05-15 11:09 UTC, kvasyaa commented on db/migrate/20230509133628_add_columns_to_employee.rb
> +    change_table :employees do |t|
it should be `create_table`

2023-05-16 09:54 UTC, vasyl-kvasnitsa requested changes

2023-05-16 09:54 UTC, vasyl-kvasnitsa commented on app/models/employee.rb
> +  validate :age_must_be_eighteen_or_above
where is a `age_must_be_eighteen_or_above ` method?

2023-05-16 09:54 UTC, vasyl-kvasnitsa commented on db/migrate/20230509133628_add_columns_to_employee.rb
> +      t.date :employed_on
Let's remove `employed_on ` and add `t.timestamps`. Always use `t.timestamps` in migrations for table creation.

2023-05-16 10:42 UTC, vasyl-kvasnitsa approved these changes

2023-05-16 10:42 UTC, vasyl-kvasnitsa commented on app/models/employee.rb
> +def employed_on_in_past
should be private method

2023-05-16 13:23 UTC, vasyl-kvasnitsa approved these changes

2023-05-16 13:56 UTC, merged